(load "multi_rep/arithmetic")

(install-scheme-number-package)
(install-rational-package)
(install-real-package)
(install-rectangular-package)
(install-polar-package)
(install-complex-package)
(install-integer-package)


(add (make-scheme-number 3) (make-scheme-number 7))
(div (make-rational 3 7) (make-rational 21 9))

(mul (make-complex-from-mag-ang 3 1.57) (make-complex-from-mag-ang 5 1.57))
(magnitude (make-complex-from-real-imag 3 4))
(equ? (make-complex-from-mag-ang 3 1.57)
      (make-complex-from-mag-ang 3 1.57))
(=zero? (make-scheme-number 0))
(=zero? (make-scheme-number 0.0))
(=zero? (make-rational 0 11))
(=zero? (make-rational 11 0))
(=zero? (make-complex-from-real-imag 0 0.1))
(=zero? (make-complex-from-real-imag 0 0))
(=zero? (make-complex-from-mag-ang 0 10))

(raise 3)
(raise (make-scheme-number 4))
(raise (make-rational 5 1))
(raise (make-rational 3 7))
(raise (make-real 3.14))

(mul (make-rational 22 7) (make-complex-from-mag-ang 5 1.57))
(mul 3 (make-complex-from-mag-ang 5 1.57))
(div 3 (make-complex-from-mag-ang 5 1.57))
(add 3 (make-complex-from-mag-ang 5 1.57))
(add 3 (make-rational 22 7))

;;; (raise (make-complex-from-mag-ang 5 3.14))
(project (make-complex-from-mag-ang 5 3.14))

(project (make-complex-from-real-imag 15 2.5))
(project (make-real 2.5))
(project (make-rational 22 7))
(drop (make-complex-from-real-imag 3 0))
(drop (make-complex-from-real-imag 3 1))
(drop (make-complex-from-real-imag 3.15 0))
(drop (make-real 3.151))
(drop (make-rational 22 7))
(drop (make-rational 30 10))
(drop (make-rational 33 3))

(mul (make-complex-from-mag-ang 3 0) (make-complex-from-mag-ang 5 0))
(mul (make-complex-from-mag-ang 3.1 0) (make-complex-from-mag-ang 5 0))
(mul (make-rational 22 7) (make-complex-from-mag-ang 5 0))
